Q.1 Write a program to create a NumPy 1D-array with 5 elements and perform basic
operations like:

a) Addition of 2 in all the element

b) Multiply 3 with all the elements

c) Divide every element by 2

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr)

#a
print(arr + 2)
#b
print( arr * 3)
#c
print( arr / 2)

[1 2 3 4 5]
[3 4 5 6 7]
[ 3  6  9 12 15]
[0.5 1.  1.5 2.  2.5]


Q.2 Questions on Basic NumPy Array:

a) Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])

b) Find the most frequent value and their indice(s) in the following arrays:

i. x = np.array([1,2,3,4,5,1,2,1,1,1])

ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

In [ ]:
import numpy as np

#2a
arr = np.array([1, 2, 3, 6, 4, 5])
print("Reversed array=", arr[::-1])

# 2b(i)
x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
value_x = np.bincount(x).argmax()
indices_x = np.where(x == value_x)[0]

print("Most frequent value in x=", value_x)
print("Indices:", indices_x)

# 2bii
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
value_y = np.bincount(y).argmax()
indices_y = np.where(y == value_y)[0]

print("Most frequent value in y=", value_y)
print("Indices:", indices_y)

Reversed array= [5 4 6 3 2 1]
Most frequent value in x= 1
Indices: [0 5 7 8 9]
Most frequent value in y= 1
Indices: [0 1 2]


Q.3 For the given 2-D array arr=np.array([10, 20, 30], [40, 50, 60], [70, 80, 90]), access
elements using row and column indices as follows:

a) Access 1st row, 2nd column

b) Access 3rd row, 1st column

In [ ]:
import numpy as np

arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

# Q.3(a)
print(arr[0, 1])

# Q.3(b)
print(arr[2, 0])

20
70


Q.4 Write program to create an 1-D NumPy array named <<Your Name>> with evenly
spaced 25 numbers from 10 to 100 using linspace(). Print the dimensions of the array,
shape, total elements, the data type of each element and total number of bytes consumed
by the array. Find the transpose of this array using reshape() attribute. Can we do the same
with T attribute?

In [ ]:
import numpy as np

shubhas = np.linspace(10, 100, 25)

print("Array:", shubhas)
print("Dimensions:", shubhas.ndim)
print("Shape:", shubhas.shape)
print("Total elements:", shubhas.size)
print("Data type:", shubhas.dtype)
print("Total bytes:", shubhas.nbytes)

transpose = shubhas.reshape(25, 1)
print("Transpose using reshape():")
print(transpose)

print("Transpose using T:")
print(shubhas.T)

Array: [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Dimensions: 1
Shape: (25,)
Total elements: 25
Data type: float64
Total bytes: 200
Transpose using reshape():
[[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]
Transpose using T:
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


Q5. Create a 2-D Array of three rows and four columns, named ucs420_<your_name>>
with following values – 10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 20, 35. Compute the mean,
median, max, min, unique elements. Reshape the array to four rows and three columns and
name it as reshaped_ ucs420_<your_name>>. Resize the array to two rows and three
columns and name it as resized_ ucs420_<your_name>>.

In [ ]:
import numpy as np

ucs420_shubhas = np.array([[10, 20, 30, 40],
                           [50, 60, 70, 80],
                           [90, 15, 20, 35]])

print("Array:")
print(ucs420_shubhas)

print("Mean:", np.mean(ucs420_shubhas))
print("Median:", np.median(ucs420_shubhas))
print("Maximum:", np.max(ucs420_shubhas))
print("Minimum:", np.min(ucs420_shubhas))
print("Unique elements:", np.unique(ucs420_shubhas))

reshaped_ucs420_shubhas = ucs420_shubhas.reshape(4, 3)
print("Reshaped array:")
print(reshaped_ucs420_shubhas)

resized_ucs420_shubhas = np.resize(ucs420_shubhas, (2, 3))
print("Resized array:")
print(resized_ucs420_shubhas)

Array:
[[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]
Mean: 43.333333333333336
Median: 37.5
Maximum: 90
Minimum: 10
Unique elements: [10 15 20 30 35 40 50 60 70 80 90]
Reshaped array:
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
Resized array:
[[10 20 30]
 [40 50 60]]
